### ISSUE TITLE
Check whether image capture is successful

### ISSUE THREAD

**Issue by a-price** [UM-ARM-Lab/arm_video_recorder#1]
The system seems to be happy recording blank frames when no USB camera is present.

**Comment by bsaund** [comment]
Please clarify. Which of the following is either not working properly, or not desirable:

1) The `video_recording.py` service server should throw the error `Error opening video stream or file` and exit if started up without any camera attached.

2) Unplugging the camera after starting the service server should log the error `Camera capture failure` instead of recording frames, but will not terminate the recording. 

3) Unplugging or turning off the video camera should result in a black screen but no error. The recording will continue.

4) Other

**Comment by a-price** [comment]
Must have been turning off the video camera. Unable to reproduce now.
