### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PeterMitrano** [UM-ARM-Lab/arm_video_recorder#5]
![2020-02-27-171854_887x420_scrot](https://user-images.githubusercontent.com/4010770/75492299-7cf25480-5985-11ea-9ae1-9ae4ab06f4b9.png)

**Comment by bsaund** [comment]
This error is due to the Aver Media Passthrough box. I suspect the mechanical switch on the lower right was not set correctly (see picture in README).

Peter and I fixed it by randomly pressing buttons on the AverMedia box until we were able to record video. When it is not in use I'll look at this more closely

**Comment by LemonPi** [comment]
This screen can also show up if the HDMI cable from the camera is connected to the OUT port instead of the IN port on the Passthrough box.
